// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-escrows.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_escrows_default = defineTool({
  name: "list_escrows",
  title: "List my escrows",
  description: "List escrows where the signed-in user is buyer or seller. Optionally filter by status.",
  inputSchema: {
    status: z.enum(["active", "completed", "refunded", "disputed"]).optional().describe("Optional status filter."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("escrows").select(
      "id, status, amount, deadline, description, buyer_address, seller_address, script_address, on_chain_status, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { escrows: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-escrow.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_escrow_default = defineTool2({
  name: "get_escrow",
  title: "Get escrow details",
  description: "Get full details for a single escrow the signed-in user participates in.",
  inputSchema: {
    escrow_id: z2.string().uuid().describe("The escrow id (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ escrow_id }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = supabaseForUser2(ctx);
    const { data: escrow, error } = await client.from("escrows").select("*").eq("id", escrow_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!escrow)
      return { content: [{ type: "text", text: "Escrow not found" }], isError: true };
    const { data: txs } = await client.from("escrow_transactions").select("id, tx_hash, action, created_at").eq("escrow_id", escrow_id).order("created_at", { ascending: false });
    return {
      content: [{ type: "text", text: JSON.stringify({ escrow, transactions: txs ?? [] }, null, 2) }],
      structuredContent: { escrow, transactions: txs ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-messages.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_messages_default = defineTool3({
  name: "list_messages",
  title: "List escrow messages",
  description: "List chat messages on an escrow the signed-in user participates in.",
  inputSchema: {
    escrow_id: z3.string().uuid(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ escrow_id, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser3(ctx).from("escrow_messages").select("id, sender_address, content, created_at").eq("escrow_id", escrow_id).order("created_at", { ascending: true }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send-message.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var send_message_default = defineTool4({
  name: "send_message",
  title: "Send escrow message",
  description: "Post a chat message to an escrow the signed-in user participates in. Uses the user's linked wallet address as sender.",
  inputSchema: {
    escrow_id: z4.string().uuid(),
    content: z4.string().trim().min(1).max(4e3)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ escrow_id, content }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = supabaseForUser4(ctx);
    const userId = ctx.getUserId();
    const { data: profile } = await client.from("profiles").select("wallet_address").eq("user_id", userId).maybeSingle();
    const sender = profile?.wallet_address;
    if (!sender)
      return {
        content: [
          {
            type: "text",
            text: "No wallet linked to your profile. Connect a wallet in the app first."
          }
        ],
        isError: true
      };
    const { data, error } = await client.from("escrow_messages").insert({ escrow_id, sender_address: sender, content }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Message sent (id ${data.id})` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jqdrthsjqckptwbalpuj";
var mcp_default = defineMcp({
  name: "trusty-deal-maker-mcp",
  title: "Trusty Deal Maker",
  version: "0.1.0",
  instructions: "Tools for the Trusty Deal Maker Cardano escrow app. Use `list_escrows` to see the signed-in user's escrows, `get_escrow` for details, `list_messages` to read chat, and `send_message` to post a message.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_escrows_default, get_escrow_default, list_messages_default, send_message_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
